iiwa:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Controllers for singular joint ------------------------------------
  # 
  # Position Controllers ---------------------------------------
  
  EffortJointInterface_J1_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_1
    pid: {p: 10.0, i: 0, d: 0, i_clamp_min: -10000, i_clamp_max: 10000}

  EffortJointInterface_J2_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_2
    pid: {p: 100.0, i: 0, d: 0, i_clamp_min: -10000, i_clamp_max: 10000}

  EffortJointInterface_J3_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_3
    pid: {p: 100, i: 0, d: 0, i_clamp_min: -10000, i_clamp_max: 10000}

  EffortJointInterface_J4_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_4
    pid: {p: 100, i: 0, d: 0, i_clamp_min: -10000, i_clamp_max: 10000}

  EffortJointInterface_J5_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_5
    pid: {p: 100, i: 0, d: 0, i_clamp_min: -10000, i_clamp_max: 10000}

  EffortJointInterface_J6_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_6
    pid: {p: 100, i: 0, d: 0, i_clamp_min: -10000, i_clamp_max: 10000}

  EffortJointInterface_J7_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_7
    pid: {p: 100, i: 0, d: 0, i_clamp_min: -10000, i_clamp_max: 10000}
